### ISSUE TITLE
Popover lowcase subtitle

### ISSUE THREAD

**Issue by alalbux** [pagarme/former-kit#185]
### Context
When `Popover` is inside `CardTitle` the subtitle with `strong` be uppercase, but expect lowercase inside popover

### Example
current:
![screenshot from 2018-08-16 17-30-34](https://user-images.githubusercontent.com/38147979/44233337-189ce500-a193-11e8-9a1f-9a48df0f640c.png)

expected:
![screenshot from 2018-08-16 17-30-10](https://user-images.githubusercontent.com/38147979/44233338-189ce500-a193-11e8-805b-9e7903a1cc19.png)

### Description
```css
/* current */
card---title  strong {
    font-weight: bold;
    text-transform: uppercase;
}

/* proposal */
card---title > strong {
    font-weight: bold;
    text-transform: uppercase;
}
```

### Requirements
- [ ] Popover lowcase subtitle
